app:
  name: "READMEOW"
  version: "1.0.0"
  env: "${APP_ENV}"

server:
  host: "0.0.0.0"
  port: "${SERVER_PORT}"
  metricPort: "${METRIC_SERVER_PORT}"
  writeTimeout: 10s
  readTimeout: 10s
  idleTimeout: 30s
  requestTimeout: 10s
  closeTimeout: 30s
  rateLimit: 1
  burst: 2

auth:
  secret: "${SECRET}"
  codeTTL: 5m
  codeAttempts: 5
  tokenTTL: 259200s

storage:
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  database: "${POSTGRES_DB}"
  timezone: "Europe/Moscow"
  host: "postgres"
  port: "${POSTGRES_PORT}"
  sslMode: "${SSL_MODE}"
  connectTimeout: 10s
  pingTimeout: 5s
  amountOfConns: 15

cache:
  host: "redis"
  port: "${REDIS_PORT}"
  password: "${REDIS_PASSWORD}"
  pingTimeout: 5s

search:
  host: "es"
  port: "${ELASTICSEARCH_PORT}"
  user: "${ELASTICSEARCH_USER}"
  password: "${ELASTICSEARCH_PASSWORD}"
  pingTimeout: 5s

email:
  name: "Readmeow Register System"
  address: "${EMAIL_ADDRESS}"
  password: "${EMAIL_PASSWORD}"
  smtpAddress: "smtp.gmail.com"
  smtpServerAddress: "smtp.gmail.com:587"

sheduler:
  widgetBulkTime: 1m
  widgetBulkTimeout: 5s
  templateBulkTime: 1m
  templateBulkTimeout: 5s
  cleanCodesTime: 1m
  cleanCodesTimeout: 5s

cloudstorage:
  cloudURL: "${CLOUDINARY_URL}"
  timeout: 30s

oauth:
  googleClientId: "${GOOGLE_CLIENT_ID}"
  googleClientSecret: "${GOOGLE_CLIENT_SECRET}"
  googleRedirectURL: "http://localhost:3333/api/auth/google/callback"  
  githubRedirectURL: "http://localhost:3333/api/auth/github/callback"
  githubClientId: "${GITHUB_CLIENT_ID}"
  githubClientSecret: "${GITHUB_CLIENT_SECRET}"
  stateTTL: 5m
  